### ISSUE TITLE
PS4 Media Player does not list files with uncompatible video or audio format

### ISSUE THREAD

**Issue by Eniff** [jellyfin/jellyfin-plugin-dlna#36]
**Describe the bug**
Playstation 4 Media Player over DLNA can't see any files which have unsupported video or audio codec. The only media that shows up are natively supported formats. This way transcoding over DLNA is impossible to select.

**System (please complete the following information):**
 - OS: Windows
 - Clients: PS4 Media Player DLNA
 - Jellyfin Version: 10.7.7
 - Playback: Direct Play, Remux, Direct Stream, Transcode
 - Hardware Acceleration: NVENC
 - Installed Plugins: none
 - Reverse Proxy: none
 - Storage: local

**To Reproduce**

1. Open media player on PS4 and navigate to Jellyfin media server
2. Can't find any videos that need remuxing, transcoding(video, audio or both) to play on PS4, only H264-AC3 etc... files appear which the PS4 natively supports.

**Expected behavior**
When the media library has a file that consists of video or audio format that the PS4 cannot play it should still show up in the PS4 Media player and it should transcode and/or remux the format which is unsupported into one that works. If for example only the audio is unsupported it should only encode that and copy the video.

**Additional context**
I have recently switched from UMS to Jellyfin and I really like the fact that you can easily use Nvenc to re-encode media, but sadly none of the videos that acutally need transcoding appear in the PS4 media player application so this bug made this application useless for me. I have tried playing around with the settings but nothing seems to work. In UMS for example you can select every trancoding option from the PS4 media player and everything shows up. But that app has other problems which made me look for alternatives. I was just wanting to let you know this bug still exists.

**Comment by FarFetchd** [comment]
I recompiled the DLNA dll to use an updated profile for the PS4. I switched the video transcoding target to mkv container (also tried mp4, same results), h264 video, aac audio. Here's where it gets weird: I found that if ffmpeg could finish before the transcoding kill timer killed it (like 15 or 20 seconds), then the video could start playing, otherwise it would just say "Cannot play the media". Unfortunately, for the video I tried, the PS4 client would then freeze (like, crash) several seconds into the playback, always at the same point.

I tried manually running Jellyfin's exact ffmpeg transcode command to get a pre-transcoded version to feed to the PS4. Jellyfin still had to remux that (the log file was named FFmpeg.Remux rather than .Transcode) and it went back to "cannot play the media", rather than the few seconds of playback.

Also worth noting: this change allowed the files to show up in the list at all. So it does seem like the ts container, or maybe ts with the particular codecs used, is a problem for PS4.

But anyways, I'm stopping here. I get the impression the PS4 media client is very particular and fragile: I'm having Jellyfin transcode to formats that AFAICT are the same as what the PS4 can play natively (and, sanity check, my laptop can get Jellyfin's web client to play videos that Jellyfin has to transcode, so it's not a problem with my Jellyfin). Maybe someone with deeper understanding of media codec/protocol stuff could find a workaround.
